[helpers]

[default]
depends = []

[default.files]
"docs" = ""
"LICENSE" = ""
"README.md" = ""

".cargo/config" = "~/.cargo/config"
".config/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
".vscode/settings.json" = "~/.vscode/settings.json"

".gitconfig" = "~/.gitconfig"
".p10k.zsh" = "~/.p10k.zsh"
".zshenv" = "~/.zshenv"
".zshrc" = "~/.zshrc"

[default.variables]
